# Generated by Django 4.0.6 on 2022-07-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('precio', models.PositiveIntegerField()),
                ('medidas', models.CharField(max_length=20)),
                ('colores', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='', verbose_name='images')),
            ],
            options={
                'ordering': ['stock'],
            },
        ),
    ]
